INSERT INTO it_machine(title,content,url,deadline,apply,applicant,image) VALUES('초.중.고 학생 교육정보화 지원','초중고 학생에게 PC, 인터넷 통신비를 지원하여 정보 소외 계층의 교육 격차를 해소하고 균등한 교육 기회 제공','https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do?wlfareInfoId=WLF00003227','2024-12-31',1,'생계급여, 의료급여, 주거급여, 교육급여 수급자, 한부모가족, 차상위계층','data:image/jpeg;');

INSERT INTO government(title,content,url,deadline,apply,department,image) VALUES('2023 꿈 하나 장학생 선발','미래 설계 장학금(초등 70만원, 중등 100만원, 고등 150만원(상, 하반기 분할 지급))','https://www.hana-nanum.com/?p=31&viewMode=view&idx=1476','2023-11-15',1,'하나금융나눔재단','data:image/png;');
INSERT INTO government(title,content,url,deadline,apply,department,image) VALUES('방과후학교 자유수강권','지원 대상자로 선정되고, 방과후학교 프로그램을 신청/수강한 경우에 1인당 연간 60만원 내외 금액 지급','https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do?wlfareInfoId=WLF00000867&wlfareInfoReldBztpCd=01','2024-12-31',1,'교육부','https:');
INSERT INTO government(title,content,url,deadline,apply,department,image) VALUES('다문화가족 방문교육 서비스','한국어 교육, 부모교육, 자녀생활교육','https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do?wlfareInfoId=WLF00003192','2023-12-31',1,'여성가족부','https://pbs.twimg.com/media/Fexsbl-aUAAlhFB.png');
INSERT INTO government(title,content,url,deadline,apply,department,image) VALUES('교육급여','연 1회 교육활동지원비 지원(초등학생(415,000원), 중학생(589,000원) 고등학생(654,000원 및 등록금/교과서))','https://www.bokjiro.go.kr/ssis-tbu/twataa/wlfareInfo/moveTWAT52011M.do?wlfareInfoId=WLF00001089','2024-06-28',1,'교육부','data:image/jpeg;');
INSERT INTO government(title,content,url,deadline,apply,department,image) VALUES('위기 다문화가족 지원','(대구광역시)기준중위소득 100% 이하 위기 다문화가족 긴급지원(1백만원)','https://www.gov.kr/portal/rcvfvrSvc/dtlEx/627000000111?administOrgCd=','2024-12-31',1,'대구광역시','data:image/png;');
INSERT INTO government(title,content,url,deadline,apply,department,image) VALUES('다문화가족 자녀 방문학습지 지원','(경기도)한글, 국어 등 학습 교재를 활용한 한글 교육, 주 1회 방문하여 교육서비스 (15분 내외)제공','https://www.gov.kr/portal/rcvfvrSvc/dtlEx/641000000122?administOrgCd=','2024-12-31',1,'경기도','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoFeTAbSu6XINggRlLmijbQyHo54459zVS8w&usqp=CAU');
INSERT INTO government(title,content,url,deadline,apply,department,image) VALUES('다문화가족 자녀 학습비 지원','(충청남도 청양군)다문화가정 자녀 만 5세~초 6학년에게 1인당 분기별 12만원 학습비 지원(학원, 학습지 등)','https://www.gov.kr/portal/rcvfvrSvc/dtlEx/459000000103?administOrgCd=','2024-12-31',1,'충청남도 청양군','https://www.liveinkorea.kr/liveinkoreaData/editor/images/002335/001_6.jpg');

INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('EBS 초등','초등교과온라인강의, 교재비는 필요','https://primary.ebs.co.kr/main/primary','2024-12-31',1,'EBS','https://play-lh.googleusercontent.com/NyhjQjZYnq0IxqD4wvyX0TiGHkz6P-9qqGYxP7C_Kkv3VFS9CFS-y0OBh1sPi-e6rMk');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('칸 아카데미','수학, 컴퓨팅 강의(영어)','https://ko.khanacademy.org/','2024-12-31',1,'Khan Academy','data:image/png;');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('EBS 중학프리미엄','중등교과온라인강의','https://mid.ebs.co.kr/premium/middle/index?gclid=EAlalQobChMlqfni95LUgQMV3wx7Bx0','2024-12-31',1,'EBS','data:image/jpeg;');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('POSTECH 중학생 온라인 멘토링','수학,과학,영어 학습 영상','https://iclass.postechx.kr/program/mentoring','2024-12-31',1,'POSTECH','data:image/png;');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('강남구청 인터넷수능방송 중등부','5만원 지불 시 1년간 사이트 내의 모든 강의 지원','https://edu.ingang.go.kr/NGLMS/Middle/UserMain.do','2024-12-31',1,'강남구청','https://edu.ingang.go.kr/NGLMS/upload//homepage/mainBanner/image/2023/09/18/1694996430378_HTozZzbHDe.jpg');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('서울 E학습터','학년별, 과목별 온라인 강의','https://cls1.edunet.net/cyber/cm/mcom/pmco000b00.do','2024-12-31',1,'한국교육학술정보원','https://i.namu.wiki/i/UAko0zkZ5VaXHnwxUsXMxdohKW8k9qxJCHQEl3IVe_YVkM0hPzKebAqhrXQQzJufFLzhVdZE1y4-U38F8xOMIw.webp');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('서울런','(서울 거주)초등 과정, 중등 과정, 고등 과정, 검정고시 과정, 멘토링 프로그램','https://slearn.seoul.go.kr/front/mainView.do','2024-12-31',1,'서울특별시청','data:image/png;');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('다문화교육포털','공교육 진입 절차 안내·홍보 및 다국어(한국어 외 14개 언어) 자료 지원, 한국 학교생활 조기 적응 지원을 위한 준비교육 지원, 입국 초기 한국어교육 지원을 위한 사업 추진 및 자료 제공, 기초학력 향상 및 이주배경 특성을 살린 인재 양성 지원','https://www.edu4mc.or.kr/','2024-12-31',1,'교육부','https://blog.kakaocdn.net/dn/cesMpo/btqEHPzB8MX/XWOpUiUsROGk2Iq2dE0Efk/img.png');
INSERT INTO education(title,content,url,deadline,apply,department,image) VALUES('다누리','교육취업 정보 -> 교육진학진로 배너에서 학부모와 학생을 위한 교육 자료를 제공','https://www.liveinkorea.kr/portal/KOR/main/main.do','2024-12-31',1,'여성가족부','https://cdn.newswatch.kr/news/photo/201511/3263_3505_3426.jpg');
